### ISSUE TITLE
Stable release plan

### ISSUE THREAD

**Issue by edonyM** [01org/TPM2.0-TSS#271]
According to the wiki on release, I checked the milestone and found them are almost completed. And I wonder to know about the stable release plan, thank you.

**Comment by flihp** [comment]
You're right about the milestone. Initially I had hoped to time a release around packaging efforts for RHEL. That work has been delayed on process: gotta go through Fedora packaging first. That and I've been planning out some pretty drastic changes. These are structural changes to the code / project, not API changes since those come from TCG. My preference would be to do our "1.0" release before digging into these changes.

I've also been thinking about a versioning scheme. Currently our 0.XX version numbers are just sequentially incrementing numbers that had meaning internally but don't mean much externally. I've been considering switching over to using the "semantic versioning" scheme: http://semver.org/

Since you asked I'm happy to hear any input you may have. There are a few odds and ends that should be cleaned up (windows build tickets) but I don't think there's anything blocking the 1.0 release at the moment.

**Comment by flihp** [comment]
Should have closed this when we did the 1.0 release months back. Dug this up since I'm starting to plan out the next release already. Closing and creating new issues / milestones for the next release.
