### ISSUE TITLE
 Resourcemgr does not support multiple processes using mutilple connection

### ISSUE THREAD

**Issue by medition** [01org/TPM2.0-TSS#295]
I have a multi-process scene, each process will create a new connection, this scenario will fail to call. After investigation, I found a bug of **resourcemgr**. In **resourcemgr.c** **2383** line, a global variable **cmdBuffer** is used to receive commands. When multiple processes send commands at the same time, the value of this global variable is unknown, resulting in a bug，I think this variable should be a **local variable**

**Comment by flihp** [comment]
Hi @medition, thanks for taking the time to look into this. The resourcemgr is causing lots of problems for us unfortunately. We're fixing the most egregious bugs that we find (see recent changes to bad socket handling and buffer overflow) but as you note, the heavy use of global data and the threading model are very broken.

I took a look at this a while back and decided that fixing the existing resourcemgr would effectively be a re-write. I started rewriting it from the ground up and we'll be releasing that as OSS very soon. Until then I'll gladly review patches to fix issues with the existing resourcemgr but it should be considered a prototype that will be deprecated in the near future and removed from the next release.

Till then I'll mark this as a bug and keep the issue open so others can see what's going on. If you do decide to submit a patch to fix this please link to this issue in the PR.

**Comment by wcarthur1** [comment]
The RM interface to the TPM is single threaded, in part, because of
limitations of the TPM.  The TPM cannot process multiple TPM commands in
parallel.

An idea:  I suspect that if, in TpmCmdServer, you move the
StartCriticalSection call up above the code that receives "the TPM command
bytes from the calling application" (find this comment), it will fix your
problem.

I don't know the nature of all the problems being found with the RM, but I
would question whether a total rewrite is needed.  My 2 cents worth.

Will

**Comment by medition** [comment]
hi，@flihp  .I'm looking forward to the next release. Before that, I will try to submit a fix PR as soon as possible to ensure that my own fix does not cause other problems. 

hi，@wcarthur1. Your idea is my initial fix method, but  there is a certain problem for this fix method, consider this scenario: a connection named **A** has been established, A "send numBytes data" to RM,then A call StartCriticalSection get lock,  after that if  A no longer send commands to the RM and doesn't close connection, no other client can communicate with RM, because they can't acquire the lock to receive command bytes，of course, this is an extreme case.  from the design point of view, the use of local variables will avoid this happening， so i think  use a local variable will be better.

**Comment by wcarthur1** [comment]
Hi, @medition.

The code is setup so that if connection A sends a command it has to get a
response or timeout.  Either way, it eventually releases the lock.  Unless
there's some path that doesn't release the lock (and I can't see one), I
don't see the scenario you point out happening.

Re local variable for the command/response buffer, I don't see how that
removes the need for a lock--the TPM is still a single resource that can
only handle one command/response at a time.  I think you still need to
allow only one connection access to the TPM at a time.

Perhaps I need to see some pseudo code for what you're thinking, but I
can't see how a local variable helps.  AFAIK, it would make the problem
worse, not better, and would consume a lot more memory.  Or maybe I need to
see your test case.

Just to make sure that you don't get confused, keep in mind that each
"connection" to the resource manager has it's own command/response buffer
in the TCTI context sitting on the application side of the socket.  The
command/response buffer that you want to make local is the single one that
is used to for communicating with the single TPM.  Before sending a command
to the TPM, we copy the command bytes from the socket to the single command
buffer.

Will

**Comment by medition** [comment]
hi, @wcarthur1 . I do not intend to remove the lock.  
The calling position of the functions (StartCriticalSection and EndCriticalSection) is same. I just make one connection one local viriable cmdBuffer。In my case,the  program's  flow is:
 1. recieve cmd data
 2.StartCriticalSection 
 3.send command to tpm, receive response from tpm and send result to client. 
 4.EndCriticalSection

And If Just  move the  StartCriticalSection call up above the code that receives "the TPM command
bytes from the calling application", the program's flow is:
 1. StartCriticalSection
 2. receive cmd data
 3. send command to tpm, receive response from tpm and send result to client. 
 4. EndCriticalSection
in this flow, if a malicious user using StartCriticalSection get the lock, then the user don't send rest command bytes any more, the user can hold the lock for any time, the lock's  hold time depending on the time the user sent the command to RM and the time RM sends command to tpm and receive response from tpm。 but in the former scenario， the lock's hold time just depending on the time RM send command to tpm and receive response from tpm,  it is **Not affected** by the user。 

And you can see commit in my fork ,  I think code may make things more clear.

**Comment by wcarthur1** [comment]
I looked at your code and your explanation.  It makes sense to me and seems
like a good fix to the issue.

I hadn't thought about the calling application being in control of data
being sent to the socket interface--good catch!

One downside is that it requires a lot of extra memory being allocated,
depending on how many apps are connected to the RM.

Another solution would be to have a timeout in recvBytes.  That wouldn't
require a local buffer to be allocated.

**Comment by dguerri** [comment]
@flihp if you need alpha/beta testers for your new resource manager, please count me in!

**Comment by flihp** [comment]
thanks @dguerri. I'm doing the paperwork to get it out the door. When it's out I'll mark the existing RM as 'deprecated' so everyone knows. I'll update the README with a link to the new one as well.

**Comment by medition** [comment]
@wcarthur1 , yes, Another solution would be to have a timeout in recvBytes.  and i think timeout receive may be complex。 And I think a small amount of memory for a connection is acceptable. 
On the other hand, I changed a few extra lines, moved them to a position behind the StartCriticalSection to protect the global variable downstreamTctiContext.

**Comment by flihp** [comment]
Hi @medition, I reviewed your PR #296. Thanks for the quick turn around on this! I broke your patch up into 2 since you're fixing two race conditions. I've closed #296, and created #299 with my re-write. If you have any feedback on my minor changes please use #299 to review. I'll leave this issue open till #299 is resolved.

**Comment by medition** [comment]
Hi @flihp ，I  have reviewed the #299 ， good job！

**Comment by flihp** [comment]
Patches are merged @medition. Thanks again for all the help!
