### ISSUE TITLE
when using tcp socket,  not set TCP_NODELAY

### ISSUE THREAD

**Issue by medition** [01org/TPM2.0-TSS#325]
when using tcp protocol, There are many places that use write write read method to comunicate with resourcemgr or simulator.  and beacuse  [Nagle's_algorithm](https://en.wikipedia.org/wiki/Nagle's_algorithm) and [TCP delayed acknowledgment](https://en.wikipedia.org/wiki/TCP_delayed_acknowledgment), will make every transmit delay some time, for me it is 40 ms.

it is better to set true for TCP_NODELAY. I am using golang as develop language, default, it set true for TCP_NODELAY . [this is related description](https://golang.org/pkg/net/#TCPConn.SetNoDelay)

**Comment by flihp** [comment]
Thanks @medition, I'll take a dig into the resources you've linked. As far as the `resourcemgr` goes though that code is pretty buggy and refactoring it will require a significant rewrite. I've nearly completed a reimplementation that will live in a separate project as soon as I get it through our internal reviews. I've got no problems with small changes like socket flags etc but I'm trying to stay away from getting bogged down in larger changes since this takes away from my work on the new implementation.

**Comment by flihp** [comment]
the resource manager has been removed from this repo. A separate repo has been setup here: https://github.com/01org/tpm2-abrmd. Closing this issue as it's no longer relevant to this repo.
