### ISSUE TITLE
Race condition In Resourcemgr.c function SockServer

### ISSUE THREAD

**Issue by medition** [01org/TPM2.0-TSS#327]
line 2749：
 rval = pthread_create( &cmdServerStruct->threadHandle, 0, (void *)serverStruct->serverFn, cmdServerStruct );

line2757:
 rval = pthread_detach( cmdServerStruct->threadHandle );

in variable cmdServerStruct will be free by  function serverStruct->serverFn

**Comment by flihp** [comment]
Ugh sorry about that. IMHO the code in resourcemgr.c is unmaintainable. I've added a blurb to the README and CHANGELOG noting that this code is deprecated and soon to be replaced. I'm happy to take patches to fix issues but I'm trying to keep from investing much time fixing this code since it will be gone in a month or so.

**Comment by medition** [comment]
@flihp  ok，i am looking forward new version of resourcemgr

**Comment by flihp** [comment]
Just released the new RM code yesterday: http://github.com/01org/tpm2-abrmd. The switch over will likely take some time but I'm happy to get reviews / feedback / bug reports / PRs.
