### ISSUE TITLE
How to run test for TPM features?

### ISSUE THREAD

**Issue by khanhnt93** [01org/TPM2.0-TSS#416]
I'm trying to run test for some TPM features. I built tpm server and tpm client in a linux machine. I followed instruction to run test but I didn't find any test for TPM features so I try to find test for tpm features example generate random number. I found test/intergration/get-random.c, it seem like generate random number test but I haven't known how to run it although I built that project.
Can you explaint to me how to run that test?
Thank you very much!

**Comment by danglus** [comment]
Hi,
  Are you familiar with the tpm2-tools project? https://github.com/01org/tpm2.0-tools
It has a special command line for generating random numbers.

Additionally, if you have a physical TPM, you can try this:

[hello_tpm.txt](https://github.com/01org/TPM2.0-TSS/files/1029368/hello_tpm.txt)

(I wrote it a while ago when I tried to learn how to use the library)

Regards,

  Dan

**Comment by khanhnt93** [comment]
Did you run it with TPM simulator? I am trying to run it with simulator server but I haven't created socket tcti context although I follow test/tpmclient/tpmclient.c.

**Comment by khanhnt93** [comment]
I am seeing tpm2.0-tools, that project exactly things I wanted. But I didn't found resource manager in TPM2.0-TSS after build it. So I can't run tools to test tpm features. Do you know how to build resource manager?

**Comment by danglus** [comment]
The old resource-managers had a lot of problems. As far as I know,  @flihp has re-written it and removed the old version. However, I have not tried to use or even download the new one. 
BTW, The tpm2_tools "-T device" flag allows you to connect directly to the TPM driver.

**Comment by liuqun** [comment]
use https://github.com/01org/tpm2_abrmd

**Comment by liuqun** [comment]
sorry , the URL should be https://github.com/01org/tpm2-abrmd

a new resource manager was named TAB RM daemon

**Comment by khanhnt93** [comment]
@danglus I use tpm2_tool with some flag to run tpm2_tool with simulator but all tpm2_tool return error, example: ERROR: rsaDecrypt failed, error code: 0x100.
I debuged and found the error code return from the simulator server, it assigned by SYS_CONTEXT->rsp_header.rsp_code. But when I run follow this step, everything is fine: run resourcemgr -> stop resouremrg -> run tpm2_tool (I hard reset to get build resourcemgr, my tpm2_tool source code is lastest ).

**Comment by khanhnt93** [comment]
I found my problem is I didn't turn on tpm chip by command tpm2_startup. That's so stupid.
Thank for your support.

**Comment by flihp** [comment]
Apologies for the slow reply. Glad you've got to the bottom of this but I want to add some details for others who may run into a similar issue and dig up this thread in the future:

Situations in which you'll need to send the TPM the `TPM2_Startup` command is pretty rare. For an TPM integrated into a platform (like a discrete chip from Infineon, or Intel's PTT) the firmware / BIOS will send this command as part of starting up the platform. But when you're running the simulator there's no firmware to do this for you.

Depending how you're setting up your debug environment you may need to startup the simulator before you can use it. If you're using the resource manager (https://github.com/01org/tpm2-abrmd) then you won't have to send the startup command from your application since the tpm2-abrmd does this for you if it's configured to use the TCTI library paired with the simulator (`tpm2-abrmd --tcti=socket).

You should only need to execute the `startup` command manually if you're running an application like the tpm2.0-tools or one you've written yourself directly against the simulator. And you'll only need to execute this command once after each time the simulator is restarted.
